title:            Chris Emmery
url:              https://cmry.github.io
permalink:        pretty
markdown:         redcarpet
timezone:         Europe/Amsterdam
paginate:         5
links:
  - name:         publ
    url:          /publications/
  - name:         code
    url:          /code/
  - name:         work
    url:          /work/
  - name:         about
    url:          /about/
social:
    github:       cmry
