title:            Chris Emmery -- Blog
url:              https://cmry.github.io
permalink:        pretty
pygments:         true
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
google_analytics: UA-21332781-7
timezone:         Europe/London
paginate:  		  5
links:
  - name:         about me
    url:          http://chris.emmery.nl/
social:
    github:       cmry
