title:            Chris Emmery
url:              https://cmry.github.io
permalink:        pretty
pygments:         true
markdown:         redcarpet2
redcarpet:
  extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
timezone:         Europe/Amsterdam
paginate:         5
links:
  - name:         publ
    url:          /publications/
  - name:         code
    url:          /code/
  - name:         work
    url:          /work/
  - name:         about
    url:          /about/
social:
    github:       cmry
