title:            Chris Emmery
url:              https://cmry.github.io
permalink:        pretty
pygments:         false
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
timezone:         Europe/Amsterdam
paginate:         5
links:
  - name:         publ
    url:          /publications/
  - name:         code
    url:          /code/
  - name:         work
    url:          /work/
  - name:         about
    url:          /about/
social:
    github:       cmry
