title:            Chris Emmery
url:              https://cmry.github.io
permalink:        pretty
pygments:         true
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
timezone:         Europe/Amsterdam
paginate:         5
links:
  - name:         about me
    url:          /about/
social:
    github:       cmry
